#!/bin/bash

db_name=$1

echo $db_name

dropdb --if-exists --interactive $db_name
createdb $db_name
psql -f sql/schema.sql $db_name

cat data/fires.csv | psql -c 'copy fires from stdin with csv header' $db_name
